version: "3"
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_CODE_PATH_HOST=./code
        - APP_CODE_PATH_CONTAINER=/var/www
    image: lakhveerbawa.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./code:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    labels:
      - "traefik.enable=false"
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./code:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
    labels:
      - traefik.http.routers.backend-staging.rule=Host(`backend-staging.castkro.com`)
      - traefik.http.routers.backend-staging.tls=true
      - traefik.http.routers.backend-staging.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    labels:
      - "traefik.enable=false"
    networks:
      - app-network
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 400M
    labels:
      - "traefik.enable=false"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
